#ifndef COMMUNICATION_PROTOCOL_H
#define COMMUNICATION_PROTOCOL_H

enum Commands {
    GET_TEST_LIST_SIZE = 1,
    GET_TEST,
    SEND_TEST_ANSWERS,
    OPEN_SESSION,
    CLOSE_SESSION,
    GET_RESULTS,
    CHANGE_CREDENTIALS,
    ADD_GROUP,
    ADD_USER,
    ERROR_DATAGRAM,
};

#endif // COMMUNICATION_PROTOCOL_H
