#ifndef COMMUNICATION_PROTOCOL_H
#define COMMUNICATION_PROTOCOL_H

namespace HotestProtocol {

enum Command {
    GET_TEST_LIST_SIZE = 1,
    GET_TEST,
    SEND_TEST_ANSWERS,
    OPEN_SESSION,
    CLOSE_SESSION,
    GET_RESULTS,
    CHANGE_CREDENTIALS,
    ADD_GROUP,
    ADD_USER,
    ERROR_DATAGRAM,
};

#define LOGIN_BYTE_SIZE 20
#define PASSWORD_BYTE_SIZE 30

enum ErrorCode {
    SUCCESS = 0,
};

}

#endif // COMMUNICATION_PROTOCOL_H
